name: Backend Cloud Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Initial checkout
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
          source_dir: html/
          destination_dir: s3://nginxhtmlfiles/
        env:
          AWS_S3_BUCKET: nginxhtmlfiles
